---
title: "IntRo to RStudio and R Markdown"
author:
  - name: "Mason A. Wirtz"
    url: https://masonwirtz.github.io
    orcid_id: 0000-0002-9408-1993
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

# Let’s get started!

### Prerequisites

The first step is to download RStudio. If you have not done so already, you can find the links and the directions on how to do this [here](https://www.rstudio.com/products/rstudio/download/). 

### Using this website

This website accompanies the workshop. All slides are available on this page, as well as on this workshop's [OSF page](https://osf.io/qp8x9/). 

The hands-on exercises are all available as R scripts under **Exercise scripts**---the exact same exercises **AND THEIR SOLUTIONS** (hidden, unless you click the *Click for answer* button under each exercise) are available **Exercises**. All solutions have thorough explanations so you can reference them again and again in the future if need be. 

When doing the exercises, you can feel free to use the provided R scripts, or feel free to make your own R scripts and simply copy/paste the exercises from the workshop website. This is entirely up to you (I personally find the exercises on the workshop website far more readable, but, like I said, however you feel most comfortable completing the exercises). The solutions are only available under the tab **Exercises**.



### Check list

Here is a summary of all the prepping steps.

-   [x] Download RStudio (essential)
-   [x] Create an OSF account [here](https://help.osf.io/hc/en-us/articles/360019929673-Create-an-OSF-Account) (optional)
-   [x] Browse the **Getting started** pages




