---
title: "Schedule"
author:
  - name: "Mason A. Wirtz"
    url: https://masonwirtz.github.io
    orcid_id: 0000-0002-9408-1993
output:
  distill::distill_article:
    toc: true
---

# Schedule 

## **Day 1. Getting wet in the coding waters: Basics of RStudio**

### **0. Introductions**

(13:00---13:45)

* Hellos, introductions
* What kind of data are we working with?
* Getting to know the website

### **1. Introduction to RStudio**

(13:45---14:15)

* Which panes exist? 
* How can I read in data?

### **2. Baby steps: Basics of coding in RStudio, part 1**

(14:15---15:00)

* Vectors
* Factors
* Data frames

### **3. Baby steps: Basics of coding in RStudio, part 2**

(15:00---16:00)

* Objects 
* Functions
* Packages

### **4. The tidier the better: Basics of coding with the Tidyverse**

(16:00---17:00)

* Tibbles
* Data wrangling with dplyr
* Piping with magritter

## **Day 2. Give me an R for reproducibility: Basics of R Markdown**

### **5. Setting up a project**

(09:00---10:00)

* How do I create an .Rproj file? 
* How can/should I structure my folders/files? 
* Relative/absolute file paths 

### **6. Code chunks in R Markdown**

(10:00---11:30)

* What is a code chunk in R Markdown? 
* Structuring code chunks 

**LUNCH**

### **7. Let’s get plotting**

(12:30---14:30)

* Plotting with ggplot2
* Saving ggplots

### **8. Reporting and reproducibility**

(14:30---15:30)

* R Markdown syntax
* Inline formatting 
* Block-level elements  

### **9. You don’t just knit with needles: Knitting in R Markdown**

(15:30---16:00)

* Knitting an HTML document
* Knitting a Word document 
* Uploading/downloading from OSF

### **10. Fun with coding**

(16:00---17:00)

* Working with your own data
* Questions, individual work

*Note: If you don't have your own data, send me a short description of your project and I will simulate data similar to the data you will be working with so that you have something to practice!*
